### PR TITLE
Add contribution guidelines

### LINKED ISSUE #1: Add a CONTRIBUTING.md
**Is your feature request related to a problem? Please describe.**
Guidance for prospective project contributors is lacking at the moment; it would be beneficial to provide documentation for them.

**Describe the solution you'd like**
a `CONTRIBUTING.md` file should be added to the [OpenCulinary project defaults repository](https://github.com/openculinary/.github/).

**Additional context**
Some useful reading references:
- https://mozillascience.github.io/working-open-workshop/contributing/
- https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md (relatively extensive)
- https://github.com/rails/rails/blob/master/CONTRIBUTING.md (relatively minimal)

### PR DESCRIPTION
**Pull request by jayaddison**
### Describe the reason for these changes and the problem that they solve
Before contributing to RecipeRadar, it can be helpful to people to offer guidance on the types of behaviour that are acceptable and welcomed by the project.

### Briefly summarize the changes
1. Add a contribution guide

### How have the changes been tested?
1. Reading through the documentation; further discussion and amendments are welcomed and will be solicited

### CODE REVIEW

**Comment by jayaddison** [comment]
@barat21 @queencitra if & when you have time, could you take a look at these contributing guidelines and let me know any improvements?  Thank you!

**Comment by jayaddison** [comment]
@regosen if & when you have time, could you take a look at these contributing guidelines and let me know any improvements? Thank you!

**Comment by jayaddison** [comment]
@SumeetMoray if & when you have time, could you take a look at these contributing guidelines and let me know any improvements? Thank you!

**Comment by SumeetMoray** [comment]
Sure ... I will look into it ! Jay !

**Comment by jayaddison** [comment]
I'm planning to merge these a little later today.  Further feedback via comments on this issue, new issues, and pull requests are all welcome.

**Comment by jayaddison** [comment]
(this set of guidelines has also been reviewed and approved by two others outside of this issue comment thread, via email and in-person respectively)

**Pull request merged**
